logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/cvnertnc/rvx-app/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"
included-patches = "'Add splash animation' 'Enable song search' 'MaterialYou' 'Premium heading'"
excluded-patches = "'Append time stamps information' 'Custom branding name YouTube' 'Custom double tap length' 'Custom package name' 'Custom seekbar color' 'Disable HDR video' 'Disable pip notification' 'Enable gradient loading screen' 'Enable old quality layout' 'Enable seekbar tapping' 'Enable wide search bar' 'Hide account menu' 'Hide captions button' 'Hide cast button' 'Hide collapse button' 'Hide comment component' 'Hide description components' 'Hide feed flyout panel' 'Hide filmstrip overlay' 'Hide floating microphone' 'Hide handle' 'Hide latest videos button' 'Hide load more button' 'Hide snack bar' 'Hide suggested video overlay' 'Hide time stamp' 'Hide tooltip content' 'Overlay buttons' 'Swipe controls' 'Theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "both"
included-patches = "'Custom branding icon YouTube Music'"
excluded-patches = "'Custom package name' 'Enable old style library shelf' 'Enable old style miniplayer' 'Spoof app version'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTubeReX]
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
build-mode = "both"
included-patches = "'Add splash animation' 'Enable song search' 'MaterialYou' 'Premium heading'"
excluded-patches = "'Append time stamps information' 'Custom branding name YouTube' 'Custom double tap length' 'Custom package name' 'Custom seekbar color' 'Disable HDR video' 'Disable pip notification' 'Enable gradient loading screen' 'Enable old quality layout' 'Enable seekbar tapping' 'Enable wide search bar' 'Hide account menu' 'Hide captions button' 'Hide cast button' 'Hide collapse button' 'Hide comment component' 'Hide description components' 'Hide feed flyout panel' 'Hide filmstrip overlay' 'Hide floating microphone' 'Hide handle' 'Hide latest videos button' 'Hide load more button' 'Hide snack bar' 'Hide suggested video overlay' 'Hide time stamp' 'Hide tooltip content' 'Overlay buttons' 'Swipe controls' 'Theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[MusicReX]
app-name = "Music"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "ReX"
build-mode = "both"
included-patches = "'Custom branding icon YouTube Music'"
excluded-patches = "'Custom package name' 'Enable old style library shelf' 'Enable old style miniplayer' 'Spoof app version'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
