logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config

[YouTube]
build-mode = "both"
included-patches = "'MaterialYou' 'Custom branding icon YouTube' 'Force custom branding wordmark header' 'Spoof app version' 'Spoof client'"
excluded-patches = "'Custom branding name YouTube' 'Custom double tap length' 'Custom package name' 'Enable gradient loading screen' 'Hide comments components' 'Description components' 'Hide feed flyout menu' 'Overlay buttons' 'Swipe controls' 'Theme' 'Disable splash animation'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

# see https://github.com/cvnertnc/rvx-app/blob/main/CONFIG.md for more detailed explanations
